import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Personal Data : Vipin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          "bg-gray-800 max-w-sm flex justify-center items-start min-h-screen p-3 min-w-full"
        }
      >
        {children}
      </body>
    </html>
  );
}
